MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/philly/gcr/resrchvc/t-chdeng/FCOS/model_hrnet_w32.pth"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "HRNET-W32"
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  HRNET:
    FPN:
      TYPE: "HRFPNv2"
      CONV_STRIDE: 2 # Match the output of HRFPN to FCOS head.
DATASETS:
  TRAIN: ("coco_2014_train_zip", "coco_2014_valminusminival_zip")
  TEST: ("coco_2014_minival_zip",)
INPUT:
  MIN_SIZE_RANGE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (180000, 240000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 8
  WARMUP_METHOD: "constant"