MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "HRNET-W32"
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  HRNET:
    FPN:
      CONV_STRIDE: 1
  FCOS:
    FPN_STRIDES: [4, 8, 16, 32, 64, 128]
    TARGET_ASSIGN: [[-1, 32], [32, 64], [64, 128], [128, 256], [256, 512], [512, 100000000]]
DATASETS:
  TRAIN: ("coco_2014_train_zip", "coco_2014_valminusminival_zip")
  TEST: ("coco_2014_minival_zip",)
INPUT:
  MIN_SIZE_RANGE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (180000, 240000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 8
  WARMUP_METHOD: "constant"